/* parser generated by jison 0.4.2 */
var tsv = (function(){
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"grid":3,"rows":4,"EOF":5,"row":6,"END_OF_LINE":7,"END_OF_LINE_WITH_NO_COLUMNS":8,"END_OF_LINE_WITH_EMPTY_COLUMN":9,"string":10,"COLUMN_EMPTY":11,"COLUMN_STRING":12,"BOF":13,"CHAR":14,"QUOTE_ON":15,"QUOTE_OFF":16,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"END_OF_LINE",8:"END_OF_LINE_WITH_NO_COLUMNS",9:"END_OF_LINE_WITH_EMPTY_COLUMN",11:"COLUMN_EMPTY",12:"COLUMN_STRING",13:"BOF",14:"CHAR",15:"QUOTE_ON",16:"QUOTE_OFF"},
productions_: [0,[3,2],[3,1],[4,1],[4,1],[4,1],[4,1],[4,2],[4,2],[4,2],[4,3],[4,3],[4,3],[6,1],[6,1],[6,1],[6,2],[6,2],[6,3],[6,3],[10,1],[10,1],[10,2],[10,3]],
performAction: function anonymous(yytext,yyleng,yylineno,yy,yystate,$$,_$) {

var $0 = $$.length - 1;
switch (yystate) {
case 1:
		return $$[$0-1];
	
break;
case 2:
		return [['']];
	
break;
case 3:
		this.$ = [$$[$0]];
	
break;
case 4:
        this.$ = [];
	
break;
case 5:
	    this.$ = [''];
	
break;
case 6:
        this.$ = [''];
    
break;
case 7:
        this.$ = $$[$0-1];
    
break;
case 8:
        $$[$0-1].push(['']);
        this.$ = $$[$0-1];
    
break;
case 9:
        $$[$0-1][$$[$0-1].length - 1].push('');
        this.$ = $$[$0-1];
    
break;
case 10:
        $$[$0-2].push($$[$0]);
        this.$ = $$[$0-2];
    
break;
case 11:
        $$[$0-2].push(['']);
        $$[$0-2].push($$[$0]);
        this.$ = $$[$0-2];
    
break;
case 12:
        $$[$0-2][$$[$0-2].length - 1].push('');
        $$[$0-2].push($$[$0]);
        this.$ = $$[$0-2];
    
break;
case 13:
		this.$ = [$$[$0].join('')];
	
break;
case 14:
		this.$ = [''];
	
break;
case 15:
	
break;
case 16:
        $$[$0-1].push('');
        this.$ = $$[$0-1];
    
break;
case 17:
        this.$ = $$[$0-1];
    
break;
case 18:
        $$[$0-2].push('');
        $$[$0-2].push($$[$0].join(''));
        this.$ = $$[$0-2];
    
break;
case 19:
        $$[$0-2].push($$[$0].join(''));
        this.$ = $$[$0-2];
    
break;
case 20:
		this.$ = [];
	
break;
case 21:
		this.$ = [$$[$0]];
	
break;
case 22:
		$$[$0-1].push($$[$0]);
		this.$ = $$[$0-1];
	
break;
case 23:
         this.$ = $$[$0-1];
     
break;
}
},
table: [{3:1,4:2,5:[1,3],6:4,7:[1,5],8:[1,6],9:[1,7],10:8,11:[1,9],12:[1,10],13:[1,11],14:[1,12],15:[1,13]},{1:[3]},{5:[1,14],7:[1,15],8:[1,16],9:[1,17]},{1:[2,2]},{5:[2,3],7:[2,3],8:[2,3],9:[2,3],11:[1,18],12:[1,19]},{5:[2,4],7:[2,4],8:[2,4],9:[2,4]},{5:[2,5],7:[2,5],8:[2,5],9:[2,5]},{5:[2,6],7:[2,6],8:[2,6],9:[2,6]},{5:[2,13],7:[2,13],8:[2,13],9:[2,13],11:[2,13],12:[2,13],14:[1,20]},{5:[2,14],7:[2,14],8:[2,14],9:[2,14],11:[2,14],12:[2,14]},{5:[2,15],7:[2,15],8:[2,15],9:[2,15],11:[2,15],12:[2,15]},{5:[2,20],7:[2,20],8:[2,20],9:[2,20],11:[2,20],12:[2,20],14:[2,20],16:[2,20]},{5:[2,21],7:[2,21],8:[2,21],9:[2,21],11:[2,21],12:[2,21],14:[2,21],16:[2,21]},{10:21,13:[1,11],14:[1,12],15:[1,13]},{1:[2,1]},{5:[2,7],6:22,7:[2,7],8:[2,7],9:[2,7],10:8,11:[1,9],12:[1,10],13:[1,11],14:[1,12],15:[1,13]},{5:[2,8],6:23,7:[2,8],8:[2,8],9:[2,8],10:8,11:[1,9],12:[1,10],13:[1,11],14:[1,12],15:[1,13]},{5:[2,9],6:24,7:[2,9],8:[2,9],9:[2,9],10:8,11:[1,9],12:[1,10],13:[1,11],14:[1,12],15:[1,13]},{5:[2,16],7:[2,16],8:[2,16],9:[2,16],10:25,11:[2,16],12:[2,16],13:[1,11],14:[1,12],15:[1,13]},{5:[2,17],7:[2,17],8:[2,17],9:[2,17],10:26,11:[2,17],12:[2,17],13:[1,11],14:[1,12],15:[1,13]},{5:[2,22],7:[2,22],8:[2,22],9:[2,22],11:[2,22],12:[2,22],14:[2,22],16:[2,22]},{14:[1,20],16:[1,27]},{5:[2,10],7:[2,10],8:[2,10],9:[2,10],11:[1,18],12:[1,19]},{5:[2,11],7:[2,11],8:[2,11],9:[2,11],11:[1,18],12:[1,19]},{5:[2,12],7:[2,12],8:[2,12],9:[2,12],11:[1,18],12:[1,19]},{5:[2,18],7:[2,18],8:[2,18],9:[2,18],11:[2,18],12:[2,18],14:[1,20]},{5:[2,19],7:[2,19],8:[2,19],9:[2,19],11:[2,19],12:[2,19],14:[1,20]},{5:[2,23],7:[2,23],8:[2,23],9:[2,23],11:[2,23],12:[2,23],14:[2,23],16:[2,23]}],
defaultActions: {3:[2,2],14:[2,1]},
parseError: function parseError(str, hash) {
    throw new Error(str);
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = "", yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == "undefined")
        this.lexer.yylloc = {};
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === "function")
        this.parseError = this.yy.parseError;
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || 1;
        if (typeof token !== "number") {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == "undefined") {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
        if (typeof action === "undefined" || !action.length || !action[0]) {
            var errStr = "";
            if (!recovering) {
                expected = [];
                for (p in table[state])
                    if (this.terminals_[p] && p > 2) {
                        expected.push("'" + this.terminals_[p] + "'");
                    }
                if (this.lexer.showPosition) {
                    errStr = "Parse error on line " + (yylineno + 1) + ":\n" + this.lexer.showPosition() + "\nExpecting " + expected.join(", ") + ", got '" + (this.terminals_[symbol] || symbol) + "'";
                } else {
                    errStr = "Parse error on line " + (yylineno + 1) + ": Unexpected " + (symbol == 1?"end of input":"'" + (this.terminals_[symbol] || symbol) + "'");
                }
                this.parseError(errStr, {text: this.lexer.match, token: this.terminals_[symbol] || symbol, line: this.lexer.yylineno, loc: yyloc, expected: expected});
            }
        }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error("Parse Error: multiple actions possible at state: " + state + ", token: " + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0)
                    recovering--;
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {first_line: lstack[lstack.length - (len || 1)].first_line, last_line: lstack[lstack.length - 1].last_line, first_column: lstack[lstack.length - (len || 1)].first_column, last_column: lstack[lstack.length - 1].last_column};
            if (ranges) {
                yyval._$.range = [lstack[lstack.length - (len || 1)].range[0], lstack[lstack.length - 1].range[1]];
            }
            r = this.performAction.call(yyval, yytext, yyleng, yylineno, this.yy, action[1], vstack, lstack);
            if (typeof r !== "undefined") {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}
};
/* generated by jison-lex 0.1.0 */
var lexer = (function(){
var lexer = {
EOF:1,
parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },
setInput:function (input) {
        this._input = input;
        this._more = this._less = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {first_line:1,first_column:0,last_line:1,last_column:0};
        if (this.options.ranges) this.yylloc.range = [0,0];
        this.offset = 0;
        return this;
    },
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) this.yylloc.range[1]++;

        this._input = this._input.slice(1);
        return ch;
    },
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length-len-1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length-1);
        this.matched = this.matched.substr(0, this.matched.length-1);

        if (lines.length-1) this.yylineno -= lines.length-1;
        var r = this.yylloc.range;

        this.yylloc = {first_line: this.yylloc.first_line,
          last_line: this.yylineno+1,
          first_column: this.yylloc.first_column,
          last_column: lines ?
              (lines.length === oldLines.length ? this.yylloc.first_column : 0) + oldLines[oldLines.length - lines.length].length - lines[0].length:
              this.yylloc.first_column - len
          };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        return this;
    },
more:function () {
        this._more = true;
        return this;
    },
less:function (n) {
        this.unput(this.match.slice(n));
    },
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20)+(next.length > 20 ? '...':'')).replace(/\n/g, "");
    },
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c+"^";
    },
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) this.done = true;

        var token,
            match,
            tempMatch,
            index,
            col,
            lines;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i=0;i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (!this.options.flex) break;
            }
        }
        if (match) {
            lines = match[0].match(/(?:\r\n?|\n).*/g);
            if (lines) this.yylineno += lines.length;
            this.yylloc = {first_line: this.yylloc.last_line,
                           last_line: this.yylineno+1,
                           first_column: this.yylloc.last_column,
                           last_column: lines ? lines[lines.length-1].length-lines[lines.length-1].match(/\r?\n?/)[0].length : this.yylloc.last_column + match[0].length};
            this.yytext += match[0];
            this.match += match[0];
            this.matches = match;
            this.yyleng = this.yytext.length;
            if (this.options.ranges) {
                this.yylloc.range = [this.offset, this.offset += this.yyleng];
            }
            this._more = false;
            this._input = this._input.slice(match[0].length);
            this.matched += match[0];
            token = this.performAction.call(this, this.yy, this, rules[index],this.conditionStack[this.conditionStack.length-1]);
            if (this.done && this._input) this.done = false;
            if (token) return token;
            else return;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line '+(this.yylineno+1)+'. Unrecognized text.\n'+this.showPosition(),
                    {text: "", token: null, line: this.yylineno});
        }
    },
lex:function lex() {
        var r = this.next();
        if (typeof r !== 'undefined') {
            return r;
        } else {
            return this.lex();
        }
    },
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },
popState:function popState() {
        return this.conditionStack.pop();
    },
_currentRules:function _currentRules() {
        return this.conditions[this.conditionStack[this.conditionStack.length-1]].rules;
    },
topState:function () {
        return this.conditionStack[this.conditionStack.length-2];
    },
pushState:function begin(condition) {
        this.begin(condition);
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 14;
break;
case 1:
    this.popState();
    return 16;

break;
case 2:
    if (yy_.yytext == this.quoteChar) {
        this.popState();
        this.begin('STRING');
        return 16;
	} else {
	    return 'CHAR';
	}

break;
case 3:
	this.popState();
	this.begin('STRING');
	return 14;

break;
case 4:
    this.quoteChar = yy_.yytext.substring(5);
	this.begin('QUOTE');
	return 15;

break;
case 5:
    this.quoteChar = yy_.yytext;
    this.popState();
	this.begin('QUOTE');
	return 15;

break;
case 6:
	this.begin('PRE_QUOTE');
	return 12;

break;
case 7:
	this.begin('PRE_QUOTE');
	return 7;

break;
case 8:return 14;
break;
case 9:
	this.popState();
	return 8;

break;
case 10:
	this.popState();
	return 7;

break;
case 11:
	this.popState();
	return 12;

break;
case 12:return 14;
break;
case 13:return 13;
break;
case 14:return 8;
break;
case 15:return 9;
break;
case 16:return 11;
break;
case 17:return 7;
break;
case 18:
	this.begin('STRING');
	return 14;

break;
case 19:
    //lexer.yy.conditionStack = [];
    return 5;

break;
}
},
rules: [/^(?:(\n|\\n))/,/^(?:([\'\"])(?=$))/,/^(?:([\'\"]))/,/^(?:(?=(\t)))/,/^(?:(:::::)([\'\"]))/,/^(?:([\'\"]))/,/^(?:(\t|\\t)(?=[\'\"]))/,/^(?:(\n|\\n)(?=[\'\"]))/,/^(?:(.))/,/^(?:(\n\n|\\n\\n))/,/^(?:(\n|\\n))/,/^(?:(\t|\\t))/,/^(?:(.))/,/^(?:(:::::))/,/^(?:(\n\n|\\n\\n))/,/^(?:(\t\n|\\t\\n))/,/^(?:(\t|\\t))/,/^(?:(\n|\\n))/,/^(?:(.))/,/^(?:$)/],
conditions: {"PRE_QUOTE":{"rules":[4,5,6,7,13,14,15,16,17,18,19],"inclusive":true},"QUOTE":{"rules":[0,1,2,3,4,6,7,8,13,14,15,16,17,18,19],"inclusive":true},"STRING":{"rules":[4,6,7,9,10,11,12,13,14,15,16,17,18,19],"inclusive":true},"INITIAL":{"rules":[4,6,7,13,14,15,16,17,18,19],"inclusive":true}}
};
return lexer;
})();
parser.lexer = lexer;
function Parser () { this.yy = {}; }Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();
if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = tsv;
exports.Parser = tsv.Parser;
exports.parse = function () { return tsv.parse.apply(tsv, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}